add bemlint to mate-scripts
mate-academy/fed pull request #50
Opened 2021-03-03 18:09 UTC by Vladimir-Beliy

2021-03-04 13:55 UTC, YuriiHoliuk requested changes

2021-03-04 13:55 UTC, YuriiHoliuk commented on mate-scripts/src/index.ts
> +  .option('-J, --noJavascript', 'lint html and css files', false)
remove. these options duplicate existing

2021-03-04 13:55 UTC, YuriiHoliuk commented on mate-scripts/src/commands/Lint.command.ts
> +    execBashCodeSilent(`npx bemlint ${filesToLint}`);
there are no bemlint installed in tasks

2021-03-17 07:06 UTC, YuriiHoliuk approved these changes
Good job!

2021-03-17 07:06 UTC, YuriiHoliuk commented on mate-scripts/configs/layout/.bemlintrc.json
> +    "node_module",
```suggestion
    "node_moduleі",
```

2021-03-17 07:06 UTC, YuriiHoliuk commented on mate-scripts/src/commands/Command.ts
>    protected projectType: ProjectTypes = ProjectTypes.None;
let's remove projectType and use it inside the config only

2021-03-17 07:06 UTC, YuriiHoliuk commented on mate-scripts/src/localScripts/repositories.ts
> +} as unknown as Record<ProjectTypes, string[]>;
💇🏼‍♂️

2021-03-17 07:06 UTC, YuriiHoliuk commented on mate-scripts/src/tools/fileSystem.ts
> +    ...config,
set default project type here(None)

2021-03-17 07:31 UTC, solaryasha commented on mate-scripts/configs/layout/.bemlintrc.json
> +    "node_module",
node_modules :)

2021-03-17 08:55 UTC, YuriiHoliuk commented on mate-scripts/configs/gitignoreTemplates/.gitignore.layout
> +.linthtmlrc.json
EOL

2021-03-17 08:55 UTC, YuriiHoliuk commented on mate-scripts/configs/gitignoreTemplates/.gitignore.layoutDOM
> +.reports
EOL

2021-03-17 08:55 UTC, YuriiHoliuk commented on mate-scripts/configs/gitignoreTemplates/.gitignore.layout
> +.linthtmlrc.json
чому додав в ignore?

2021-03-17 08:55 UTC, YuriiHoliuk commented on mate-scripts/configs/gitignoreTemplates/.gitignore.layoutDOM
> +.reports
що за reports з крапкою? там є просто reports його точно не треба в ігнор

2021-03-17 08:55 UTC, YuriiHoliuk commented on mate-scripts/configs/layout/.linthtmlrc.json
> +{
він чомусь копіювався з node_modules, так як ти зробив краще, але глянь чому було ьак, напевне є причина

2021-03-17 08:55 UTC, YuriiHoliuk commented on mate-scripts/src/localScripts/repositories.ts
> +};
то я так, можна було не змінювати

2021-03-17 08:55 UTC, YuriiHoliuk commented on mate-scripts/update.js
> +// exec('npm i -D @@mate-academy/eslint-config@latest');
remove file or uncomment

2021-03-17 10:59 UTC, merged